name: citizen_review_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.5.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Add your external dependencies here
  http: ^0.13.5  # For making HTTP requests
  shared_preferences: ^2.0.15  # For storing data locally (like JWT tokens)
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true  # Ensures Material Icons are included

# Assets and other configurations can be added here
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg

# To add custom fonts to your application, add a fonts section here:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
